# Generated by Django 3.0.7 on 2020-08-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table=None,
        ),
    ]
