# Generated by Django 3.0.7 on 2020-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0002_auto_20200817_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('c_email', models.EmailField(max_length=30)),
                ('c_cont', models.IntegerField()),
                ('gender', models.CharField(max_length=50, null=True)),
                ('add', models.CharField(max_length=50)),
            ],
        ),
    ]
