# Generated by Django 3.0.7 on 2020-08-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0003_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_email', models.EmailField(max_length=254)),
                ('passw', models.CharField(max_length=10)),
            ],
        ),
    ]
