# Generated by Django 3.0.7 on 2020-09-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='c_email',
            field=models.EmailField(max_length=254),
        ),
    ]
