# Generated by Django 3.0.7 on 2020-09-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0007_requarement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requarement',
            name='lorryType',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
