# Generated by Django 3.0.7 on 2020-09-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0009_auto_20200916_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requarement',
            name='user',
        ),
    ]
