# Generated by Django 3.0.7 on 2020-09-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0010_remove_requarement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requarement',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
