# Generated by Django 3.0.7 on 2020-09-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0012_payment_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_ids',
        ),
    ]
