# Generated by Django 3.0.7 on 2020-09-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0013_delete_payment_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='l_name',
        ),
    ]
