# Generated by Django 3.0.7 on 2020-09-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0014_auto_20200928_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='f_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='l_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
