# Generated by Django 3.0.7 on 2020-09-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manag_app', '0015_auto_20200928_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='passw',
        ),
        migrations.RemoveField(
            model_name='register',
            name='repassw',
        ),
    ]
